# https://taskfile.dev

version: '3'

tasks:
  sln-add:
    desc: Add a project to the solution
    cmds:
      - dotnet sln add {{ .CLI_ARGS | default .USER_WORKING_DIR }}
  sln-list:
    desc: List all projects in the solution
    cmds:
      - dotnet sln list
  sln-remove:
    desc: Remove a project from the solution
    cmds:
      - dotnet sln remove {{ .CLI_ARGS | default .USER_WORKING_DIR }}
  add-examples:
    desc: Add all example projects to the root solution file
    cmds:
      - find src/examples -iname '*.csproj' -exec dotnet sln add {} \;
  clean:
    desc: Remove the generated _site folder
    cmds:
      - rm -r ./_site
  build:processor:
    cmds:
      - dotnet build -c Release src/Xabbo.Docs -o templates/xabbo/plugins
  build:
    desc: Build the site
    deps: [build:processor]
    cmds:
      - docfx build docfx.json
  rebuild:
    desc: Rebuild the site
    cmds:
      - task: clean
      - task: build
  serve-only:
    desc: Serve the site without building
    cmds:
      - docfx serve _site
  serve:
    desc: Build and serve the site
    deps: [build]
    cmds:
      - task: serve-only
