# https://taskfile.dev

version: '3'

tasks:
  list-projects:
    desc: List all projects in the solution
    cmds:
      - dotnet sln list
  add-examples:
    desc: Add all example projects to the root solution file
    cmds:
      - find src/examples -iname '*.csproj' -exec dotnet sln add {} \;
  clean:
    desc: Remove the generated _site folder
    cmds:
      - rm -r ./_site
  build:processor:
    cmds:
      - dotnet build -c Release src/Xabbo.Docs -o templates/xabbo/plugins
  build:
    desc: Build the site
    deps: [build:processor]
    cmds:
      - docfx build docfx.json
  serve-only:
    desc: Serve the site without building
    cmds:
      - docfx serve _site
  serve:
    desc: Build and serve the site
    deps: [build]
    cmds:
      - task: serve-only
